### ISSUE TITLE
Prevent update on initial install

### ISSUE THREAD

**Issue by microadam** [driftyco/ionic-service-deploy#25]
Hello,

Not sure if I am missing something here, but if I transfer an app to my phone and upload the same version of the app to ionic and then deploy that version, should the update happen after first run? I would have thought it would detect that they are the same version and not do the update. Seems a little odd as an end user to download an app just to have it update immediately.

My workflow is:

```
ionic upload
/* go into ionic dashboard and deploy uploaded version */
ionic run ios -cs --device
```

Thanks a lot!

**Comment by ericb** [comment]
This is a known issues that is being addressed in the next update.

**Comment by microadam** [comment]
Great, thanks for the update!

**Comment by ericb** [comment]
@microadam This has been addressed with the latest deploy updates.

If you're exact concern was during testing, each time you `ionic run` (installing the app on a device or emulator) any previous deploy will be ignored. If the deployed version is not the same as the one currently deployed via the dashboard, it will still need to download once before ignoring. This allows you to ignore initial deploys on the phone while developing locally but still allow you to test using deploys.

If you were more concerned about preventing an App Store version from automatically downloading an update, you can check out the docs for [binary versioning](http://docs.ionic.io/v1.0/docs/deploy-binary-versioning). 

Cheers :beers:

**Comment by microadam** [comment]
@ericb Thanks a lot. Still having issues with this though. On the latest versions of everything (service deploy, service core and plugin deploy).

I have created a new version of my app and set the config.xml to have version `0.1.0` as the version number. I have generated an IPA using `ionic build ios` and then exported an archive from xCode.

I have then done an `ionic upload` and edited my version on the ionic dashboard to have iOS binary version as `0.1.0`. I have then deployed the app in the dashboard.

I have then installed the IPA on my phone and the first thing the app does is a version check, at which point it believes there is a new version and updates it. This is what I am trying to prevent.

Can you see if I am doing anything wrong in this flow?

Thanks a lot

**Comment by ericb** [comment]
@microadam You either aren't running the updated components (it can say the versions are up to date, but unless you correctly prepare the ios platform or remove and re-add the ios platform, the old components will still be in the build, even though the latest components are available), or the version isn't being set in the app correctly -- It will show the version labels in the xcode logs when it checks for updates. You can verify there.

**Comment by microadam** [comment]
Thanks a lot, removing and re-adding the platform solved it!
